version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: user_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: signup
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - usernet

  backend:
    build: ./user-service/server
    container_name: user_backend
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - ./user-service/server/.env
    volumes:
      - ./user-service/server/uploads:/app/uploads
    depends_on:
      - mysql
    networks:
      - usernet

  frontend:
    build: ./frontend
    container_name: user_frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - usernet

networks:
  usernet:

volumes:
  mysql_data:
  